# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/workspace/tt_metal/third_party/umd;/workspace/tt_metal/third_party/umd/.build/clang-static-analyzer")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_ALL "umd-runtime;umd-dev")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENTS_GROUPING "IGNORE")
set(CPACK_COMPONENT_UMD-DEV_DEPENDS "umd-runtime")
set(CPACK_COMPONENT_UMD-DEV_DESCRIPTION "Headers and CMake files for UMD")
set(CPACK_COMPONENT_UMD-DEV_DISABLED "FALSE")
set(CPACK_COMPONENT_UMD-DEV_DISPLAY_NAME "Tenstorrent UMD Development")
set(CPACK_COMPONENT_UMD-DEV_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_UMD-DEV_HIDDEN "FALSE")
set(CPACK_COMPONENT_UMD-DEV_REQUIRED "FALSE")
set(CPACK_COMPONENT_UMD-PYTHON_DEPENDS "umd-runtime")
set(CPACK_COMPONENT_UMD-PYTHON_DESCRIPTION "Python bindings for Tenstorrent UMD")
set(CPACK_COMPONENT_UMD-PYTHON_DISABLED "FALSE")
set(CPACK_COMPONENT_UMD-PYTHON_DISPLAY_NAME "Python FHS Bindings")
set(CPACK_COMPONENT_UMD-PYTHON_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_UMD-PYTHON_HIDDEN "FALSE")
set(CPACK_COMPONENT_UMD-PYTHON_REQUIRED "FALSE")
set(CPACK_COMPONENT_UMD-RUNTIME_DESCRIPTION "Runtime library for Tenstorrent devices")
set(CPACK_COMPONENT_UMD-RUNTIME_DISABLED "FALSE")
set(CPACK_COMPONENT_UMD-RUNTIME_DISPLAY_NAME "Tenstorrent UMD Runtime")
set(CPACK_COMPONENT_UMD-RUNTIME_DOWNLOADED "FALSE")
set(CPACK_COMPONENT_UMD-RUNTIME_HIDDEN "FALSE")
set(CPACK_COMPONENT_UMD-RUNTIME_REQUIRED "FALSE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS "ON")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "support@tenstorrent.com")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEBIAN_UMD_DEV_PACKAGE_NAME "umd-dev")
set(CPACK_DEBIAN_UMD_PYTHON_PACKAGE_NAME "umd-python")
set(CPACK_DEBIAN_UMD_RUNTIME_PACKAGE_NAME "umd-runtime")
set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-4.1/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "umd built using CMake")
set(CPACK_GENERATOR "DEB;RPM")
set(CPACK_GENERATOR "DEB;RPM")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/workspace/tt_metal/third_party/umd/.build/clang-static-analyzer;umd;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/workspace/tt_metal/third_party/umd/cmake")
set(CPACK_NSIS_DISPLAY_NAME "tt_umd 0.9.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "tt_umd 0.9.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/workspace/tt_metal/third_party/umd/.build/clang-static-analyzer/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "support@tenstorrent.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-4.1/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Tenstorrent User Mode Driver")
set(CPACK_PACKAGE_FILE_NAME "tt_umd-0.9.1-Linux")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/tenstorrent/tt-umd")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "tt_umd 0.9.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "tt_umd 0.9.1")
set(CPACK_PACKAGE_NAME "tt_umd")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Tenstorrent, Inc.")
set(CPACK_PACKAGE_VERSION "0.9.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "9")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-4.1/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-4.1/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-4.1/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_COMPONENT_INSTALL "ON")
set(CPACK_RPM_ENABLE_COMPONENT_DEPENDS "ON")
set(CPACK_RPM_PACKAGE_GROUP "Development/Libraries")
set(CPACK_RPM_PACKAGE_LICENSE "Apache-2.0")
set(CPACK_RPM_UMD_DEV_PACKAGE_NAME "umd-dev")
set(CPACK_RPM_UMD_PYTHON_PACKAGE_NAME "umd-python")
set(CPACK_RPM_UMD_RUNTIME_PACKAGE_NAME "umd-runtime")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/workspace/tt_metal/third_party/umd/.build/clang-static-analyzer/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/workspace/tt_metal/third_party/umd/.build/clang-static-analyzer/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
