name: 'Restore Build Cache'
description: 'Restores file timestamps, build cache, and handles force rebuild flag'

inputs:
  cache-key-prefix:
    description: 'Prefix for the cache key (e.g., build-tests, build-tests-wheel)'
    required: true
  docker-name:
    description: 'Docker image name'
    required: true
  docker-tag:
    description: 'Docker tag'
    required: true
  build-type:
    description: 'Build type (Release, Debug, etc.)'
    required: true
  build-output-dir:
    description: 'Build output directory path'
    required: true
    default: 'build'
  repo-path:
    description: 'Path to the repository (relative to workspace root)'
    required: false
    default: '.'

outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Restore file timestamps to match git commit
      shell: bash
      working-directory: ${{ inputs.repo-path }}
      run: |
        git config --global --add safe.directory "$PWD"
        mkdir -p build
        touch build/compile_commands.json
        git ls-files | while IFS= read -r file; do
          touch -d @$(git log -1 --format=%at -- "$file") "$file"
        done

    - name: Restore build cache
      uses: actions/cache/restore@v4
      id: cache
      with:
        path: |
          ${{ inputs.repo-path }}/${{ inputs.build-output-dir }}
          ${{ inputs.repo-path }}/.cpmcache
        # yamllint disable rule:line-length
        key: ${{ inputs.cache-key-prefix }}-${{ inputs.docker-name }}-${{ inputs.docker-tag }}-${{ github.head_ref != '' && github.head_ref || github.ref_name }}-${{ inputs.build-type }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ inputs.docker-name }}-${{ inputs.docker-tag }}-${{ github.head_ref != '' && github.head_ref || github.ref_name }}-${{ inputs.build-type }}-
          ${{ inputs.cache-key-prefix }}-${{ inputs.docker-name }}-${{ inputs.docker-tag }}-main-${{ inputs.build-type }}-
        # yamllint enable rule:line-length

    - name: Force rebuild if user set [force-rebuild] in commit message
      shell: bash
      working-directory: ${{ inputs.repo-path }}
      run: |
        # For PRs, check the actual PR head commit, not the merge commit
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
        else
          COMMIT_SHA="HEAD"
        fi
        COMMIT_MSG=$(git log -1 --pretty=%B "$COMMIT_SHA")
        echo "Checking commit: $COMMIT_SHA"
        echo "Commit message: $COMMIT_MSG"
        if echo "$COMMIT_MSG" | grep -q "\[force-rebuild\]"; then
          echo "User requested force rebuild via [force-rebuild] in commit message."
          echo "Removing build cache..."
          rm -rf ${{ inputs.build-output-dir }}
        else
          echo "No [force-rebuild] flag found in commit message."
        fi
