function(FIND_AND_SET_CLANG20)
    find_program(CLANGPP_20 clang++-20)
    find_program(CLANG_20 clang-20)

    if(NOT CLANGPP_20 OR NOT CLANG_20)
        message(FATAL_ERROR "Clang-20 not found. Make sure you have clang-20 and clang++-20 installed and in your PATH")
    endif()

    set(CMAKE_CXX_COMPILER "${CLANGPP_20}" PARENT_SCOPE)
    set(CMAKE_C_COMPILER "${CLANG_20}" PARENT_SCOPE)
endfunction()

function(CHECK_COMPILERS)
    message(STATUS "Checking compilers")

    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++" CACHE STRING "CXX FLAGS for clang")
        if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "20.0.0")
            message(WARNING "Clang-20 or higher is suggested for tt-umd")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "12.0.0")
            message(WARNING "GCC-12 or higher is suggested for tt-umd")
        endif()
    else()
        message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID} ! Only Clang and GCC are supported")
    endif()
endfunction()
