name: Nix build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: nix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tt-umd
        run: nix build .# --print-build-logs
