# Run Pre-commit Hooks
name: Run Pre-commit Hooks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

jobs:
  pre-commit:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Fetch all history so 'origin/main' is available

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache pre-commit environments
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run Pre-commit and Fix Issues
        run: pre-commit run --from-ref origin/main --to-ref HEAD
        env:
          PRE_COMMIT_HOME: ~/.cache/pre-commit
